### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Ihor0k** [v-omelai/planning-poker#1]
- https://github.com/v-omelai/planning-poker/blob/77aa6d2a9e4316fe4c978573c632ff6f3dfe9958/app.py#L20
According to REST, GET is an idempotent method. It should not cause any state change in the backend. So the endpoint that creates a new session must be POST.

- https://github.com/v-omelai/planning-poker/blob/77aa6d2a9e4316fe4c978573c632ff6f3dfe9958/app.py#L42-L48
You can reset the state at any time by sending POST /start/<key>, not sure it's an expected behavior.

- Authentication/authorization is missing.

**Comment by v-omelai** [comment]
@Ihor0k 

First of all, thank you for your response!

I think you took this project too seriously :)

FYI: 

- It's just a proof of concept (PoC)
- Feel free to contribute if you know how to do it better

You're right about this line:
`r.set(key, json.dumps({'started': None, 'participants': {}}))`

I'm familiar with best practices, but I don't see the point in complicating everything in this case (see [KISS principle](https://en.wikipedia.org/wiki/KISS_principle))

The `/session/` endpoint returns HTML, which is why I used the `GET` method there

Of course, we could add a separate `POST` endpoint specifically for session creation. The question is - why?

Perhaps you might have some suggestions?
